from PyQt5 import QtCore, QtWidgets, QtGui
from QtOrthoViewer import *
from QtSegmentationViewer import QtSegmentationViewer
from VtkBase import VtkBase
from ViewersConnection import ViewersConnection


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.vtkBaseClass = VtkBase()
        self.QtSagittalOrthoViewer = QtOrthoViewer(self.vtkBaseClass, SLICE_ORIENTATION_YZ, "Sagital")
        self.QtCoronalOrthoViewer = QtOrthoViewer(self.vtkBaseClass, SLICE_ORIENTATION_XZ, "Coronal")
        self.QtAxialOrthoViewer = QtOrthoViewer(self.vtkBaseClass, SLICE_ORIENTATION_XY, "Axial")
        self.QtSagittalOrthoViewer.setFixedSize(200, 200)
        self.QtAxialOrthoViewer.setFixedSize(200, 200)
        self.QtCoronalOrthoViewer.setFixedSize(200, 200)
        self.QtSegmentationViewer = QtSegmentationViewer(self.vtkBaseClass, label="3D")
        self.QtSegmentationViewer.setFixedSize(200, 200)
        self.ViewersConnection = ViewersConnection(self.vtkBaseClass)
        self.ViewersConnection.add_orthogonal_viewer(self.QtSagittalOrthoViewer.get_viewer())
        self.ViewersConnection.add_orthogonal_viewer(self.QtCoronalOrthoViewer.get_viewer())
        self.ViewersConnection.add_orthogonal_viewer(self.QtAxialOrthoViewer.get_viewer())
        self.ViewersConnection.add_segmentation_viewer(self.QtSegmentationViewer.get_viewer())

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(70, 0))
        self.frame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame.setStyleSheet("background-color:rgb(90, 99, 156)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setStyleSheet("border:0px;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/database_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_27.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_27.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_27.setStyleSheet("background-color:#E2BBE9;\n"
                                         "border-radius: 25px;")
        self.pushButton_27.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/display_purple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_27.setIcon(icon1)
        self.pushButton_27.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_3.addWidget(self.pushButton_27)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_26.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_26.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_26.setStyleSheet("border:0px;")
        self.pushButton_26.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/addDicom_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon2)
        self.pushButton_26.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_3.addWidget(self.pushButton_26)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(270, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_17 = QtWidgets.QFrame(self.frame_2)
        self.frame_17.setMinimumSize(QtCore.QSize(250, 70))
        self.frame_17.setMaximumSize(QtCore.QSize(250, 70))
        self.frame_17.setStyleSheet("background-color: #5A639C;\n"
                                    "border-radius: 30px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout.addWidget(self.frame_17)
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 225))
        self.frame_12.setStyleSheet("background-color: #FFFFFF;\n"
                                    "\n"
                                    "")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setGeometry(QtCore.QRect(0, 20, 250, 161))
        self.frame_13.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(250, 200))
        self.frame_13.setStyleSheet("background-color: #E8C9ED;\n"
                                    "border-radius: 15px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_13)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 251, 152))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/colorfilter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/ruler.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/Ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("assets/Arrow 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon6)
        self.pushButton_13.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("assets/freeDraw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("assets/Angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon8)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("assets/gallery-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon9)
        self.pushButton_15.setIconSize(QtCore.QSize(45, 40))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("assets/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon10)
        self.pushButton_14.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("assets/Rectangle 20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon11)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("assets/A.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon12)
        self.pushButton_9.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        self.label_8.setGeometry(QtCore.QRect(40, 0, 171, 31))
        self.label_8.setStyleSheet("font: 87 16pt \"Roboto\" \"bold\";\n"
                                   "background-color: rgb(119, 118, 179);\n"
                                   "color:#FFFFFF;\n"
                                   "border-radius: 15px;")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_14.setStyleSheet("background-color: #FFFFFF;\n" "\n" "")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setGeometry(QtCore.QRect(0, 20, 250, 71))
        self.frame_16.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_16.setMaximumSize(QtCore.QSize(250, 200))
        self.frame_16.setStyleSheet("background-color: #E8C9ED;\n" "border-radius: 15px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_16)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 251, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("assets/brightness.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon13)
        self.pushButton_16.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 0, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("assets/refresh-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon14)
        self.pushButton_28.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_3.addWidget(self.pushButton_28, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("assets/displacement.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon15)
        self.pushButton_17.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setGeometry(QtCore.QRect(40, 0, 171, 31))
        self.label_10.setStyleSheet(
            "font: 87 16pt \"Roboto\" \"bold\";\n" "background-color: rgb(119, 118, 179);\n" "color:#FFFFFF;\n" "border-radius: 15px;")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.frame_14)
        self.frame_22 = QtWidgets.QFrame(self.frame_2)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 225))
        self.frame_22.setStyleSheet("background-color: #FFFFFF;\n""\n"
                                    "")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setGeometry(QtCore.QRect(0, 20, 250, 131))
        self.frame_23.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_23.setMaximumSize(QtCore.QSize(250, 200))
        self.frame_23.setStyleSheet("background-color: #E8C9ED;\n"
                                    "border-radius: 15px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.frame_23)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 10, 251, 121))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.four_grid_images_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("assets/2x2 grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.four_grid_images_btn.setIcon(icon16)
        self.four_grid_images_btn.setIconSize(QtCore.QSize(45, 45))
        self.four_grid_images_btn.setObjectName("four_grid_images_btn")
        self.four_grid_images_btn.clicked.connect(self.display_four_images)
        self.gridLayout_7.addWidget(self.four_grid_images_btn, 1, 1, 1, 1)
        self.one_image_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("assets/Rectangle 24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.one_image_btn.setIcon(icon17)
        self.one_image_btn.setIconSize(QtCore.QSize(45, 45))
        self.one_image_btn.setObjectName("one_image_btn")
        self.one_image_btn.clicked.connect(self.display_one_image)
        self.gridLayout_7.addWidget(self.one_image_btn, 0, 0, 1, 1)
        self.two_image_horizontal_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("assets/2x1grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.two_image_horizontal_btn.setIcon(icon18)
        self.two_image_horizontal_btn.setIconSize(QtCore.QSize(35, 35))
        self.two_image_horizontal_btn.setObjectName("two_image_horizontal_btn")
        self.gridLayout_7.addWidget(self.two_image_horizontal_btn, 0, 3, 1, 1)
        self.two_image_horizontal_btn.clicked.connect(self.display_two_images)
        self.three_image_vertical_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("assets/1x3grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.three_image_vertical_btn.setIcon(icon19)
        self.three_image_vertical_btn.setIconSize(QtCore.QSize(40, 40))
        self.three_image_vertical_btn.setObjectName("three_image_vertical_btn")
        self.three_image_vertical_btn.clicked.connect(self.display_three_images)
        self.gridLayout_7.addWidget(self.three_image_vertical_btn, 0, 2, 1, 1)
        self.two_image_vertical_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("assets/1x2grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.two_image_vertical_btn.setIcon(icon20)
        self.two_image_vertical_btn.setIconSize(QtCore.QSize(40, 40))
        self.two_image_vertical_btn.setObjectName("two_image_vertical_btn")
        self.two_image_vertical_btn.clicked.connect(self.display_two_images)

        self.gridLayout_7.addWidget(self.two_image_vertical_btn, 0, 1, 1, 1)
        self.t_images_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("assets/1up_2downgrid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_images_btn.setIcon(icon21)
        self.t_images_btn.setIconSize(QtCore.QSize(45, 45))
        self.t_images_btn.setObjectName("t_images_btn")
        self.t_images_btn.clicked.connect(self.display_three_images)
        self.gridLayout_7.addWidget(self.t_images_btn, 1, 0, 1, 1)
        self.t_inverted_images_btn = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("assets/1+2grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t_inverted_images_btn.setIcon(icon22)
        self.t_inverted_images_btn.setIconSize(QtCore.QSize(45, 45))
        self.t_inverted_images_btn.setObjectName("t_inverted_images_btn")
        self.t_inverted_images_btn.clicked.connect(self.display_three_images)
        self.gridLayout_7.addWidget(self.t_inverted_images_btn, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_22)
        self.label_14.setGeometry(QtCore.QRect(40, 0, 171, 31))
        self.label_14.setStyleSheet("font: 87 16pt \"Roboto\" \"bold\";\n"
                                    "background-color: rgb(119, 118, 179);\n"
                                    "color:#FFFFFF;\n"
                                    "border-radius: 15px;")
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.frame_22)
        self.horizontalLayout.addWidget(self.frame_2)
        self.main_splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.frame_3 = QtWidgets.QWidget(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(1100, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.frame_3.setObjectName("frame_3")
        self.central_layout = QtWidgets.QHBoxLayout(self.frame_3)
        self.frame_3.setLayout(self.central_layout)
        self.mainLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.mainLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Herramientas"))
        self.label_10.setText(_translate("MainWindow", "Funciones"))
        self.label_14.setText(_translate("MainWindow", "Disposición"))

    def display_one_image(self):
        # Eliminar cualquier layout existente en frame_3
        if self.frame_3.layout():
            self.frame_3.layout().deleteLater()

        # Crear un nuevo QtOrthoViewer
        self.vtkBaseClass = VtkBase()
        single_viewer = QtOrthoViewer(self.vtkBaseClass, SLICE_ORIENTATION_YZ, "Sagital")

        # Conectar el viewer a VtkBase
        self.ViewersConnection = ViewersConnection(self.vtkBaseClass)
        self.ViewersConnection.add_orthogonal_viewer(single_viewer.get_viewer())

        # Crear un layout y agregar el viewer
        layout = QVBoxLayout()
        layout.addWidget(single_viewer)
        self.frame_3.setLayout(layout)

        # Mostrar el viewer y el frame_3
        single_viewer.show()
        self.frame_3.show()

    def display_two_images(self):
        pass

    def display_three_images(self):
        pass

    def display_four_images(self):
        if (not hasattr(self, 'QtSagittalOrthoViewer') or
                not hasattr(self, 'QtAxialOrthoViewer') or
                not hasattr(self, 'QtCoronalOrthoViewer') or
                not hasattr(self, 'QtSegmentationViewer')):
            print("Uno o más visualizadores no están inicializados.")
            return

        # Crear y configurar los splitters verticales
        left_splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)
        left_splitter.addWidget(self.QtSagittalOrthoViewer)
        left_splitter.addWidget(self.QtAxialOrthoViewer)

        right_splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)
        right_splitter.addWidget(self.QtCoronalOrthoViewer)
        right_splitter.addWidget(self.QtSegmentationViewer)

        # Crear el splitter principal
        main_splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        main_splitter.addWidget(left_splitter)
        main_splitter.addWidget(right_splitter)

        # Agregar el splitter principal al layout horizontal
        self.central_layout.addWidget(main_splitter)
        self.frame_3.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
