# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialogoTagsSubida.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(657, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(90, 99, 156);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.uploadTags_table = QtWidgets.QTableWidget(Dialog)
        self.uploadTags_table.setStyleSheet("QTableWidget {\n"
"    font-family: \'Roboto\', sans-serif;\n"
"\n"
"    border-radius: 10px;\n"
"    gridline-color: #FFFFFF;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #FFFFFF;\n"
"    color: #5A639C;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: black;\n"
"    font-weight: regular;\n"
"    background-color: #FFFFFF;\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #B0B0B0;\n"
"}\n"
"\n"
"/* Centrar verticalmente el contenido de las celdas */\n"
"QTableWidget::item {\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
"/* Asegurar que el texto se centre horizontalmente */\n"
"QTableWidget {\n"
"    qproperty-textElideMode: ElideNone;\n"
"    qproperty-showGrid: false;\n"
"}\n"
"\n"
"/* Estilo para el viewport del QTableWidget */\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #5A639C;\n"
"    border: none;\n"
"}\n"
"")
        self.uploadTags_table.setObjectName("uploadTags_table")
        self.uploadTags_table.setColumnCount(3)
        self.uploadTags_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.uploadTags_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uploadTags_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.uploadTags_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.uploadTags_table)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelButton_uploadTags = QtWidgets.QPushButton(self.widget_2)
        self.cancelButton_uploadTags.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton_uploadTags.setFont(font)
        self.cancelButton_uploadTags.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton_uploadTags.setStyleSheet("background-color: rgb(90, 99, 156);\n"
"color:#ffffff;\n"
"border-radius:15px;")
        self.cancelButton_uploadTags.setObjectName("cancelButton_uploadTags")
        self.horizontalLayout.addWidget(self.cancelButton_uploadTags)
        self.acceptButton_uploadTags = QtWidgets.QPushButton(self.widget_2)
        self.acceptButton_uploadTags.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.acceptButton_uploadTags.setFont(font)
        self.acceptButton_uploadTags.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acceptButton_uploadTags.setStyleSheet("background-color: rgb(90, 99, 156);\n"
"color:#ffffff;\n"
"border-radius:15px;")
        self.acceptButton_uploadTags.setObjectName("acceptButton_uploadTags")
        self.horizontalLayout.addWidget(self.acceptButton_uploadTags)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setSpacing(50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.numImagenes = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.numImagenes.setFont(font)
        self.numImagenes.setObjectName("numImagenes")
        self.horizontalLayout_4.addWidget(self.numImagenes)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Carga de Estudio"))
        self.label.setText(_translate("Dialog", "Estudio por cargar (TAC)"))
        item = self.uploadTags_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Campo"))
        item = self.uploadTags_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Valor"))
        self.cancelButton_uploadTags.setText(_translate("Dialog", "Cancelar"))
        self.acceptButton_uploadTags.setText(_translate("Dialog", "Aceptar"))
        self.numImagenes.setText(_translate("Dialog", "Imágenes cargada"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
